# -----------------------------------------------------------------------------
# MantisBT Travis-CI build configuration file
# -----------------------------------------------------------------------------

language: php
